added JS API task
austincqdo/jsdojo1 pull request #2
Opened 2019-07-08 08:52 UTC by austincqdo

2019-07-08 08:54 UTC, austincqdo commented
https://bozuman.cybozu.com/g/schedule/view.csp?event=1747885&bdate=2019-07-08&uid=2304&gid=&referer_key=cb33b15242d6af7c34586de8ca67b6ef

here is a link to the app template used (in attachments).

2019-07-19 02:52 UTC, mmiyahara requested changes
I put some comments. Please check!

2019-07-19 02:52 UTC, mmiyahara commented on js_pt1/dest/desktop/js/script5+1.js
> +		let actions = [
Use `const` instead.

2019-07-19 02:52 UTC, mmiyahara commented on js_pt1/dest/desktop/js/script5+1.js
> +		let rows = [];
You can use `const` in this case as the value it holds is not immutable.

> The const declaration creates a read-only reference to a value.
> It does not mean the value it holds is immutable, just that the variable identifier cannot be reassigned.
> For instance, in the case where the content is an object, this means the object's contents (e.g., its properties) can be altered.
> [const - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const#Description)

2019-07-19 02:52 UTC, mmiyahara commented on js_pt1/dest/desktop/js/script5+1.js
> +					'value': undefined
The value of the `'value'` should be `''` as the value of the MULTI_LINE_TEXT field is `''` when it's empty.
Please check the value of MULTI_LINE_TEXT field when it's empty.

2019-07-23 09:13 UTC, mmiyahara approved these changes
Great! Please merge it into the `mater` branch.

2019-08-06 08:32 UTC, merged